### ISSUE TITLE
点赞列表 article-heart 容器宽度溢出

### ISSUE THREAD

**Issue by tony-studio** [itwanger/paicoding#54]
**bug描述**

点赞列表 article-heart 容器宽度溢出，造成移动端页面出现横向滚动条

**复现**

移动端访问 https://paicoding.com/article/detail/197 页面即可复现

bug产生原因（若您已发现具体的bug产生原因，请直接贴上，也可以提merge进行修复）

限制 div class="article-heart bg-color-white" max-width 并水平居中，或改变呈现形式。

**Comment by liuyueyi** [comment]
已修复
