### ISSUE TITLE
com.github.paicoding.forum.service.statistics.listener.UserStatisticEventListener 疑问

### ISSUE THREAD

**Issue by Qing-Yu-SH** [itwanger/paicoding#66]
`@Async
    @EventListener(ArticleMsgEvent.class)
    public void publishArticleListener(ArticleMsgEvent<ArticleDO> event) {
        ArticleEventEnum type = event.getType();
        if (type == ArticleEventEnum.ONLINE || type == ArticleEventEnum.OFFLINE || type == ArticleEventEnum.DELETE) {
            Long userId = event.getContent().getUserId();
            int count = articleDao.countArticleByUser(userId);
            RedisClient.hSet(CountConstants.USER_STATISTIC_INFO + userId, CountConstants.READ_COUNT, count);
        }
    }`
这边统计的应该是用户发表的文章数量吧。那 field 中的键应该是 CountConstants.ARTICLE_COUNT 吧？

**Comment by liuyueyi** [comment]
是个bug，已更新；感谢指出
