### ISSUE TITLE
点赞线程安全问题

### ISSUE THREAD

**Issue by winter1215** [itwanger/paicoding#68]
**bug描述**

连续多次的点击点赞按钮会出现点赞数跳动的bug

**复现**

bug复现步骤:
连续多次的点击点赞按钮

bug产生原因（若您已发现具体的bug产生原因，请直接贴上，也可以提merge进行修复）

可能是点赞代码块没有做线程安全的控制,可能使用 synconized(userId) { vote code }会解决此问题

**Comment by z15511002058** [comment]
我猜跟后台没关系纯前端问题 点赞接口没有返回点赞后的数量 如果不刷新页面的话点赞数值只会在第一次加载页面时从后台获取 所以我推测跟后台完全没关系

**Comment by winter1215** [comment]
建议仔细阅读issue
