### ISSUE TITLE
部署完后js css无法跨域加载

### ISSUE THREAD

**Issue by promise777** [itwanger/paicoding#80]
**讨论主题**
请问这个怎么解决
![Snipaste_2024-07-21_00-58-35](https://github.com/user-attachments/assets/9e212161-ebd3-4a61-8caa-1920bcd62135)

**Comment by liuyueyi** [comment]
问题原因：

- 生产环境的静态文件是存储再cdn上的，目的是减少服务器的网络开销，提高网站的访问速度
- 私有的oss是配置了防盗链的，并不是所有的域名都可以直接方案

解决方法：

方案1：将oss获取静态文件改为本地获取

![image](https://github.com/user-attachments/assets/8378456c-95a7-4c28-8724-0f9591233cd1)

源码配置中的 prod/application-config.yml 文件中的 view.site.oss，将其中设置为空，参考 resources/application-config.yml 中的设置方式即可；这样静态文件就直接从本地获取，不会从cdn上去下载，就不会出现跨域问题了


方案2：将静态文件上传到自己的oss

- 将 paicoding-ui模块下的 resources/static 下的所有文件，上传到你自己的oss上
- 找到 prod/application-config.yml 文件，将 view.site.oss 替换为你自己的oss静态文件的访问路径
